[build]
  environment = { BASE_URL = "https://www.geekco.fr" }

[[redirects]]
  from = "https://geekco.netlify.app/*"
  to = "https://www.geekco.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://geekco.netlify.app/*"
  to = "https://www.geekco.fr/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "Deny"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
