[build]
  environment = { BASE_URL = "https://www.geekco.fr" }

[[redirects]]
  from = "https://geekco.netlify.app/*"
  to = "https://www.geekco.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://geekco.netlify.app/*"
  to = "https://www.geekco.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/posts/en/how-to-use-gitlab-ci-and-php-stan-to-improve-code-quality-in-your-symfony-project"
  to = "/posts/how-to-use-gitlab-ci-and-php-stan-to-improve-code-quality-in-your-symfony-project"
  status = 301
  force = true

[[redirects]]
  from = "/posts/en/how-to-add-flutter-integration-test-in-a-ci-with-github-action"
  to = "/posts/how-to-add-flutter-integration-test-in-a-ci-with-github-action"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "Deny"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"