name: main

on: [push, workflow_dispatch]

jobs:
  main:
    name: main
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: prepare
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: prepare
      - name: build
        run: |
          npm install --global pnpm
          pnpm install
          pnpm run generate
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        if: steps.prepare.outputs.branch == 'main'
        with:
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 3