name: Nuxt CI

on: [push, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      FB_APP_ID: ${{ secrets.FB_APP_ID }}
      STORYBLOK_ACCESS_TOKEN: ${{ secrets.STORYBLOK_ACCESS_TOKEN }}
      BASE_URL: 'http://localhost:3000'
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: build
        run: yarn generate
      - name: lighthouse
        run: yarn run lhci
      - name: e2e tests
        run: yarn run test:e2e:ci
      - name: percy
        run: yarn run percy:ci
